
[editor]
mouse = true
cursorline = true
scrolloff = 0
auto-info = false

[editor.indent-guides]
render = true

[editor.cursor-shape]
insert = "bar"
normal = "block"

[editor.file-picker]
hidden = false
ignore = true

[editor.lsp]
display-signature-help-docs = false
display-inlay-hints = false

[editor.statusline]
right = ["version-control", "spacer", "diagnostics", "selections", "position", "position-percentage", "total-line-numbers", "file-encoding"]

[keys.normal]
0 = "goto_first_nonwhitespace"
G = "goto_last_line"
H = "goto_window_top"
M = "goto_window_center"
L = "goto_window_bottom"
g = { e = "goto_line_end" }
"left" = ":bp"
"right" = ":bn"
D = ["select_mode", "goto_line_end", "delete_selection"]
x = "delete_selection"
X = "no_op"
V = ["select_mode", "extend_to_line_bounds"]
"A-left" = ["select_prev_sibling", "select_mode"]
"A-right" = ["select_next_sibling", "select_mode"]
"?" = ["global_search"]
"space" = { d = "workspace_diagnostics_picker", F = "file_picker_in_current_buffer_directory" }
up = "no_op"
down = "no_op"

[keys.select]
g = { e = "goto_line_end" }
"0" = "goto_first_nonwhitespace"
"G" = "goto_last_line"
"D" = ["select_mode", "goto_line_end", "delete_selection"]
"x" = "delete_selection"
"X" = "no_op"
"V" = ["extend_to_line_bounds"]

[keys.insert]
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"
pageup = "no_op"
pagedown = "no_op"
home = "no_op"
end = "no_op"
